/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0984e3",
        "primary-hover": "#0773c5",
        danger: "#d63031",
        surface: "#f5f6fa",
        ink: "#2d3436",
        muted: "#636e72",
        "ping-bg": "#fdfdfd",
        "ping-dark": "#08283b",
        "ping-heading": "#041620",
        "ping-body": "#395362",
        "ping-body-primary": "#08283b",
        "ping-placeholder": "#5a6f7c",
        "ping-input-bg": "#ececeb",
        "ping-input-border": "#b2bcc2",
        "ping-stroke": "#e6eaeb",
        "ping-orange": "#b54000",
        "ping-error-bg": "#fde8e8",
        "ping-error-border": "#c81e1e",
        "ping-error-text": "#c81e1e",
        "ping-badge-bg": "#b2bcc2",
        "ping-badge-stroke": "#395362",
        "ping-badge-purple-bg": "#edebfe",
        "ping-badge-purple-border": "#ac94fa",
        "ping-badge-purple-text": "#5521b5",
        "ping-badge-red-bg": "#fde8e8",
        "ping-badge-red-border": "#f98080",
        "ping-badge-red-text": "#9b1c1c",
        "ping-badge-green-bg": "#def7ec",
        "ping-badge-green-border": "#31c48d",
        "ping-badge-green-text": "#03543f",
        "ping-badge-yellow-bg": "#ffebb0",
        "ping-badge-yellow-border": "#fecb33",
        "ping-badge-yellow-text": "#8c6900",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
