-- Set test admin password for QA/API tests (admin@amalitech.com).
-- Password: QAAdmin@123 (hash generated by Spring BCryptPasswordEncoder)
-- Docker: Get-Content scripts\set-test-admin-password.sql | docker exec -i communityboard-db-staging psql -U postgres -d communityboard

UPDATE users
SET password = '$2a$10$J9CD0lrAp9aqO7Gm7RmMnu59LQhh/0tZwgXKytzVQGlx4uVCYi9MS'
WHERE email = 'admin@amalitech.com';
