name: Terraform Infrastructure

on:
  push:
    branches: [main, develop]
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init & Apply (Staging)
        if: github.ref == 'refs/heads/develop'
        working-directory: ./terraform/environments/staging
        run: |
          terraform init
          terraform apply -var-file="staging.tfvars" -auto-approve

      - name: Terraform Init & Apply (Production)
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform/environments/production
        run: |
          terraform init
          terraform apply -var-file="production.tfvars" -auto-approve
